name: 2 Promote to Preprod 🚀

concurrency: preprod

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version 📦'
        required: true
        type: string
      replicas:
        description: 'Número de replicas a desplegar 🤖🤖'
        required: false
        type: string
        default: "1"      
        
env:
  VERSION: ${{ inputs.version }}
  HASH: ${{ github.sha }}
  AMBIENTE: preprod
  MULE_ENV: Preprod
  ENV: test

jobs:
  MuleDeploy:
    runs-on: ubuntu-22.04
    environment: Preprod   
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
        
    - if: ${{ ! startsWith(inputs.version, 'fix/') }}
      name: "Validar número de versión"
      run: |
        echo "Version ${{inputs.version}}"
        [[ "${{inputs.version}}" =~ ^([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9]*)$ ]] && echo "Correcto" || exit 1
        echo "Validando si ya existe un release"
        ! git ls-remote --exit-code --heads origin releases/${{inputs.version}}
    
    - name: Configurar Git
      run: |
        git config --global user.name 'Github'
        git config --global user.email 'workflow@noreply.github.com'
        git branch --show-current

    # Si el tag es nuevo lo crea
    # Si ya existe el tag, lo elimina del repositorio (local y remoto) y lo crea de nuevo en el ultimo commit de main
    - if: ${{ ! startsWith(inputs.version, 'fix') }}
      name: "Crear tag de pre-release"
      run: |
        
        echo "VER=${{inputs.version}}" >> $GITHUB_ENV
                
        ############ Si es versión normal.
        if [[ ! "${{inputs.version}}" =~ ^([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9]*)$ ]]; \
        then exit 1; fi
        git tag --force ${{inputs.version}} 
        git push origin ${{inputs.version}} --force     

    - if: ${{ startsWith(inputs.version, 'fix') }}
      name: "Crear tag de pre-release (desde fix)"
      run: |
        ############ Si es hotfix
        VER=(${{ inputs.version }})
        VER="${VER:4:10}"
        # En caso de que se esté tratando con una rama de hotfix, se hace checkout a esa rama.
        if [[ ${{inputs.version}} == "fix/"$VER ]]; then git checkout ${{inputs.version}}; fi
        # La variable VER, contendrá el input. Y en caso de que ese contenido comience con fix/ se recortará.
        if [[ ${{inputs.version}} == "fix/"$VER ]]; then git tag --force $VER; fi 
        if [[ ${{inputs.version}} == "fix/"$VER ]]; then git push origin $VER --force; fi

    # Se crea el pre-release
    # Si ya existe, primero se elimina y se crea de nuevo
    - if: ${{ startsWith(inputs.version, 'fix') }}
      name: "Release (desde fix)"
      run: |
        VER=(${{ inputs.version }})
        VER="${VER:4:10}"
        (gh release create $VER --title $VER -F CHANGELOG.md --prerelease) || \
        (gh release delete $VER -y && gh release create $VER --title $VER -F CHANGELOG.md --prerelease)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Se crea el pre-release
    # Si ya existe, primero se elimina y se crea de nuevo
    - name: "Release"
      if: ${{ ! startsWith(inputs.version, 'fix') }}
      run: |
        (gh release create ${{ inputs.version }} --title ${{ inputs.version }} -F CHANGELOG.md --prerelease) || \
        (gh release delete ${{ inputs.version }} -y && gh release create ${{ inputs.version }} --title ${{ inputs.version }} -F CHANGELOG.md --prerelease)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    ############ MULE #############
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '8'
        cache: 'maven'
    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v20
      with:
        servers: |
          [
            {
              "id": "anypoint-exchange-v3", 
              "username": "~~~Client~~~",
              "password": "${{secrets.MULE_CLIENT_ID}}~?~${{secrets.MULE_CLIENT_SECRET}}"
            },
            {
              "id": "MuleRepository", 
              "username": "${{secrets.MULE_REPO_USER}}",
              "password": "${{secrets.MULE_REPO_PASSWORD}}"
            }
          ]
        repositories: |
          [
            {
              "id": "MuleRepository",
              "url": "https://repository.mulesoft.org/nexus-ee/content/repositories/releases-ee/"
            }
          ]
    - name: Obtener nombre de proyecto
      run: |
        import os, re
        from xml.etree import ElementTree

        # Obtiene nombre del POM
        namespaces = {'xmlns' : 'http://maven.apache.org/POM/4.0.0'}
        tree = ElementTree.parse("pom.xml")
        root = tree.getroot()
        name = root.find("./xmlns:name", namespaces=namespaces)
        print(f"pom/name: {name}")

        # Convirte nombre a un nombre DNS valido
        nombre = re.sub(r"[^a-zA-Z0-9]+", "-", name.text).lower()
        print(f"nombre_limpio: {nombre}")      

        # Escribe variable
        print("Escribiendo nombre en GITHUB_ENV")
        with open(os.getenv('GITHUB_ENV'), "a") as github_env:
          github_env.write(f"nombre_limpio={nombre}")
      shell: python
    - name: "Construir y Publicar en Exchange"
      run: |
        mvn versions:set -DnewVersion=$VERSION-$HASH
        mvn clean deploy -Denv=$ENV -Dlicense.skip=true || echo "No se publico en exchange"
    - name: "Publicar resultados de pruebas"
      uses: EnricoMi/publish-unit-test-result-action@v2.0.0
      if: always()
      with:
        junit_files: "target/surefire-reports/*.xml"
    - name: "Desplegar"
      run: |
        mvn clean package deploy\
         -DmuleDeploy\
         -DskipTests\
         -Dlicense.skip=true\
         -Dclientid=${{secrets.MULE_CLIENT_ID}}\
         -Dclientsecret=${{secrets.MULE_CLIENT_SECRET}}\
         -Dappname=${{env.nombre_limpio}}-$AMBIENTE\
         -Denvironment=$MULE_ENV\
         -Danypoint_client_id=${{secrets.ANYPOINT_CLIENT_ID_PRE}}\
         -Danypoint_client_secret=${{secrets.ANYPOINT_CLIENT_SECRET_PRE}}\
         -Dreplicas=${{inputs.replicas}}\
         -Denv=$ENV