name: 3 Promote to Production 📦🚀

concurrency: production

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version 📦'
        required: true
        type: string
      replicas:
        description: 'Número de replicas a desplegar 🤖🤖'
        required: false
        type: string
        default: "1"      
        
env:
  VERSION: ${{ inputs.version }}
  AMBIENTE: production
  MULE_ENV: Production
  HASH: ${{ github.sha }}
  ENV: prod

jobs:
  MuleTest:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '8'
        cache: 'maven'
    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v20
      with:
        servers: |
          [
            {
              "id": "anypoint-exchange", 
              "username": "~~~Client~~~",
              "password": "${{secrets.MULE_CLIENT_ID}}~?~${{secrets.MULE_CLIENT_SECRET}}"
            },
            {
              "id": "MuleRepository", 
              "username": "${{secrets.MULE_REPO_USER}}",
              "password": "${{secrets.MULE_REPO_PASSWORD}}"
            }
          ]
        repositories: |
          [
            {
              "id": "MuleRepository",
              "url": "https://repository.mulesoft.org/nexus-ee/content/repositories/releases-ee/"
            }
          ]
    - name: "Asignar versión fix/x.x."
      if: ${{contains(github.ref, 'fix')}}
      run: |
        echo "# Version: ${GITHUB_REF:15}-$HASH" >> $GITHUB_STEP_SUMMARY
    - name: "Asignar versión main"
      if: ${{!contains(github.ref, 'fix')}}
      run: |
        echo "# Version: $VERSION-$HASH" >> $GITHUB_STEP_SUMMARY
    - name: "Changelog"
      run: |
        cat CHANGELOG.md >> $GITHUB_STEP_SUMMARY
    - name: "Pruebas MUnit"
      run: |
        mvn clean test -Denv=$ENV -Dlicense.skip=true
    - name: "Publicar resultados de pruebas"
      uses: EnricoMi/publish-unit-test-result-action@v2.0.0
      if: always()
      with:
        junit_files: "target/surefire-reports/*.xml"
  MuleDeploy:
    needs: MuleTest
    runs-on: ubuntu-22.04
    environment: Production
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: "Validar número de versión"
      run: |
        echo "Version ${{inputs.version}}"
        [[ "${{inputs.version}}" =~ ^([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9]*).*$ ]] && echo "Correcto" || exit 1
        echo "> Validando si existe el pre-release"
        ! git tag ${{inputs.version}}

    
    - name: "Configurar Git"
      run: |
        git config --global user.name 'Github'
        git config --global user.email 'workflow@noreply.github.com'
        git branch --show-current
        git checkout ${{inputs.version}}
        git fetch
        git branch -a --contains tags/${{inputs.version}}

    - name: "Crear rama release"
      run: |
        git checkout ${{inputs.version}}
        git checkout -b releases/${{inputs.version}}
        # Copiando los workflows actualizados...
        git checkout main .github/workflows/manual_deploy-pre.yml
        git checkout main .github/workflows/manual_deploy-prod.yml
        git checkout main .github/workflows/manual_fix.yml
        git checkout main .github/workflows/manual_redeploy.yml
        git checkout main .github/workflows/push-manual_deploy-dev.yml
        git commit -m "ci(github): Se agregan workflows actualizados" || echo "Sin cambios"
        git diff HEAD^ HEAD
        git tag --force ${{inputs.version}} 
        git push origin releases/${{inputs.version}} || echo "No se pudo crear la rama de release"
        git push origin ${{inputs.version}} --force || echo "No se pudo crear el tag de release"

    # To do: Eliminar rama de fix


    # Se actualiza el release marcado como pre-release
    - name: Release
      run: |
        gh release delete ${{inputs.version}} -y || echo "No hay release por eliminar"
        gh release create ${{inputs.version}} --title ${{inputs.version}} -F CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '8'
        cache: 'maven'
    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v20
      with:
        servers: |
          [
            {
              "id": "anypoint-exchange", 
              "username": "~~~Client~~~",
              "password": "${{secrets.MULE_CLIENT_ID}}~?~${{secrets.MULE_CLIENT_SECRET}}"
            },
            {
              "id": "MuleRepository", 
              "username": "${{secrets.MULE_REPO_USER}}",
              "password": "${{secrets.MULE_REPO_PASSWORD}}"
            }
          ]
        repositories: |
          [
            {
              "id": "MuleRepository",
              "url": "https://repository.mulesoft.org/nexus-ee/content/repositories/releases-ee/"
            }
          ]
    - name: Obtener nombre de proyecto
      run: |
        import os, re
        from xml.etree import ElementTree

        # Obtiene nombre del POM
        namespaces = {'xmlns' : 'http://maven.apache.org/POM/4.0.0'}
        tree = ElementTree.parse("pom.xml")
        root = tree.getroot()
        name = root.find("./xmlns:name", namespaces=namespaces)
        print(f"pom/name: {name}")

        # Convirte nombre a un nombre DNS valido
        nombre = re.sub(r"[^a-zA-Z0-9]+", "-", name.text).lower()
        print(f"nombre_limpio: {nombre}")      

        # Escribe variable
        print("Escribiendo nombre en GITHUB_ENV")
        with open(os.getenv('GITHUB_ENV'), "a") as github_env:
          github_env.write(f"nombre_limpio={nombre}")
      shell: python
    - name: "Construir y Publicar en Exchange"
      run: |
        mvn versions:set -DnewVersion=$VERSION
        mvn clean deploy -DskipTests -Denv=$ENV -Dlicense.skip=true || echo "No se publico en exchange"
    - name: "Desplegar"
      run: |
        mvn clean package deploy\
         -DmuleDeploy\
         -DskipTests\
         -Dlicense.skip=true\
         -Dclientid=${{secrets.MULE_CLIENT_ID}}\
         -Dclientsecret=${{secrets.MULE_CLIENT_SECRET}}\
         -Dappname=${{env.nombre_limpio}}-$AMBIENTE\
         -Denvironment=$MULE_ENV\
         -Danypoint_client_id=${{secrets.ANYPOINT_CLIENT_ID_PROD}}\
         -Danypoint_client_secret=${{secrets.ANYPOINT_CLIENT_SECRET_PROD}}\
         -Dreplicas=${{inputs.replicas}}\
         -Denv=$ENV